# Generated by Django 3.2.8 on 2021-10-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFieldReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.IntegerField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('shift_date', models.DateField(blank=True, null=True)),
                ('call_time_1', models.DateTimeField(blank=True, null=True)),
                ('release_time_1', models.DateTimeField(blank=True, null=True)),
                ('call_time_2', models.DateTimeField(blank=True, null=True)),
                ('release_time_2', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('cust_region', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_division', models.CharField(blank=True, max_length=128, null=True)),
                ('cust_subdivision', models.CharField(blank=True, max_length=128, null=True)),
                ('cust_tieuplocation', models.CharField(blank=True, max_length=128, null=True)),
                ('cust_machine_availability', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, max_length=5000, null=True)),
                ('ir_rep', models.CharField(blank=True, max_length=250, null=True)),
                ('vandhana_rep', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_dttm', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_dttm', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
